# Generated by Django 4.0.6 on 2022-07-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='number',
            new_name='phone_number',
        ),
    ]
