# Generated by Django 4.0.6 on 2022-07-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_rename_complete_task_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
